# Docker Compose configuration for Provet API service

services:
  provet-api:
    build:
      context: .
      dockerfile: Dockerfile
      # Multi-stage build with test stage that runs unit tests before creating the runtime image
    image: provet-api:latest
    container_name: provet-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./solution:/app/solution
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped 